### ISSUE TITLE
Domain with multiple disks seem to only backup the 1st one

### ISSUE THREAD

**Issue by aruhier** [aruhier/virt-backup#28]
Doing a backup of a domain with multiple disks seem to only backup the 1st disk.

**Comment by aruhier** [comment]
For the details, the bug could be triggered with a config like this:
```
hosts:
    - host-a
    - host-b
      disks:
        - vda
        - vdb
    - host: host-c
      disks:
        - vda
```
The `disks` parameter was buggy in a way that it would use the last one defined, and apply it for every hosts. With this example, it means that it kept only the `disks` filter used for `host-c`. The result would be that it only backup the disk `vda` for `host-a`, `host-b` and `host-c`.
